---
AWSTemplateFormatVersion: '2010-09-09'
Description: Mobile App CICD

Parameters:
  SourceBranchName:
    Type: String
    Default: master
  CodeCommitMobileRepoName:
    Type: String
    Default: student-attendance-mobile
  CodeCommitMobileRepoDescription:
    Type: String
    Default: student-attendance-mobile
  CodeCommitWebRepoName:
    Type: String
    Default: student-attendance-web
  CodeCommitWebRepoDescription:
    Type: String
    Default: student-attendance-web
  CodeCommitAPIInfraRepoName:
    Type: String
    Default: student-attendance-api-infra
  CodeCommitAPIInfraRepoDescription:
    Type: String
    Default: student-attendance-api-infra
  BuildTimeoutInMinutes:
    Type: Number
    Default: 15
  AppModuleName:
    Type: String
    Default: app
  OutputApkKeyName:
    Type: String
    Default: app.apk

Resources:
# AWS CodeCommit Git repository to store the mobile app's code
  CodeRepoMobile:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Ref CodeCommitMobileRepoDescription
      RepositoryName: !Ref CodeCommitMobileRepoName
###################################################################
# AWS CodeCommit Git repository to store the web app's code
  CodeRepoWeb:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Ref CodeCommitWebRepoDescription
      RepositoryName: !Ref CodeCommitWebRepoName
###################################################################
# AWS CodeCommit Git repository to store API and Infra
  CodeRepoAPIInfra:
     Type: AWS::CodeCommit::Repository
     Properties:
       RepositoryDescription: !Ref CodeCommitAPIInfraRepoDescription
       RepositoryName: !Ref CodeCommitAPIInfraRepoName
###################################################################
 
#Cloudformation Service Role
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: CloudFormationPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: "*"
            Resource: "*"
            Effect: Allow     
Outputs:
   CodeRepoMobileCloneUrlHttp:
     Description: "Mobile Code Repo HTTP Clone URL"
     Value: !GetAtt CodeRepoMobile.CloneUrlHttp
   CodeRepoWebCloneUrlHttp:
     Description: "Web Code Repo HTTP Clone URL"
     Value: !GetAtt CodeRepoWeb.CloneUrlHttp